name = "mintableerc20"
version = "<%= package.version %>"
description = "Official Cannon build for @openzeppelin/contracts/token/ERC20/ERC20.sol contract"
keywords = ["erc20", "token"]

[setting.salt]
defaultValue = "ERC20"

[setting.name]
defaultValue = "Token"

[setting.symbol]
defaultValue = "TKN"

[contract.token]
artifact = "MintableERC20"
args = ["<%= settings.name %>", "<%= settings.symbol %>"]
salt = "<%= settings.salt %>"
step = 1
