name: Upload Website to IPFS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  upload-ipfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: '20.5.1'
      - run: npm ci
      - run: npm run build
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - run: echo "${{ vars.NEXT_ENV }}" > .env.local
      - run: cd packages/website && npm run build
      - run: echo "${{ vars.PYTHON_UPLOAD_TO_IPFS }}" > upload-to-ipfs.py
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install simplejson requests-toolbelt
      - run: cd packages/website && python3 ../../upload-to-ipfs.py "${{ secrets.IPFS_URL }}" out
