name: Upload Website to IPFS

on:
  pull_request:
    branches: [main]

jobs:
  upload-ipfs:
    runs-on: ubuntu-latest
    permissions: 
       pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: '20.5.1'
      - run: npm ci
      - run: npm run build
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - run: echo "${{ vars.NEXT_ENV }}" > packages/website/.env.local
      - run: cd packages/website && npm run build
      - env:
          PYTHON_UPLOAD_TO_IPFS: ${{ vars.PYTHON_UPLOAD_TO_IPFS }}
        run: echo "$PYTHON_UPLOAD_TO_IPFS" > upload-to-ipfs.py
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install simplejson requests-toolbelt
      - run: |
          echo 'UPLOAD_RESULT<<EOF' >> $GITHUB_OUTPUT
          cd packages/website && python3 ../../upload-to-ipfs.py "${{ secrets.IPFS_URL }}" out | tee -a $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        id: upload
      - name: Comment on the result
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{ steps.upload.outputs.UPLOAD_RESULT }}
          comment_tag: ipfs_upload_result
